version: '3.4'

services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis
  
  discountdb:
    image: postgres
    
  orderdb:
    image: mcr.microsoft.com/mssql/server
    
  rabbitmq:
    image: rabbitmq:3-management
  
  portainer:
    image: portainer/portainer-ce
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
  
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
      
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      
  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile
      
  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile
      
  webapp.traditional:
    image: ${DOCKER_REGISTRY-}traditionalwebapp
    build:
      context: .
      dockerfile: WebApps/TraditionalWebApp/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
